# spring boot configuration:
spring:
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: password
    hikari:
      pool-name: HikariCP
      auto-commit: false
      connection-timeout: 5000
      max-lifetime: 600000
      maximum-pool-size: 50
      minimum-idle: 5
